In [1]:
from tables import *
class Particle(IsDescription):
    pos  = UInt64Col()      # Signed 64-bit integer
    length  = UInt16Col()     # Unsigned short integer

In [18]:
h5file = open_file('tutorial.h5', mode='w', title='Test file')

In [19]:
table = h5file.create_table("/", 'indices',Particle, 'index of the array')

In [4]:
from sklearn import preprocessing
scalar = preprocessing.MinMaxScaler()
data = [[1,2,3],[3,4,5],[6,7,8]]
scalar.fit(data)
scalar.transform(data)

array([[0. , 0. , 0. ],
       [0.4, 0.4, 0.4],
       [1. , 1. , 1. ]])

In [5]:
X=[[1,2,3],[2,3,4],[4,5,6]]

In [7]:
import numpy as np
np.add(X,50)

array([[51, 52, 53],
       [52, 53, 54],
       [54, 55, 56]])

In [20]:
h5file

File(filename=tutorial.h5, title='Test file', mode='w', root_uep='/', filters=Filters(complevel=0, shuffle=False, bitshuffle=False, fletcher32=False, least_significant_digit=None))
/ (RootGroup) 'Test file'
/indices (Table(0,)) 'index of the array'
  description := {
  "length": UInt16Col(shape=(), dflt=0, pos=0),
  "pos": UInt64Col(shape=(), dflt=0, pos=1)}
  byteorder := 'little'
  chunkshape := (6553,)

In [21]:
particle = table.row

In [22]:
for i in range(10):
    particle['pos'] = i
    particle['length'] = 1
    particle.append()

In [23]:
table.flush()

In [24]:
table = h5file.get_node('/indices')

In [27]:
table[0]['length']

1

In [14]:
[x['pos'] for x in table.iterrows()]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [30]:
h5file.close()

In [1]:
from codesearcher import *

Using TensorFlow backend.


In [2]:
conf = getattr(configs, "get_config")()
cs = CodeSearcher(conf)

In [12]:
cs.load_codebase()
m,a,t = cs.load_use_data()
m,a,t = cs.pad(m,6),cs.pad(a,30),cs.pad(t,50)

2018-11-21 19:44:12,325: codesearcher: INFO: Loading codebase (chunk size=2000000)..
2018-11-21 19:44:12,325: codesearcher: INFO: Loading use data..
2018-11-21 19:44:12,326: codesearcher: INFO: methname
2018-11-21 19:44:12,745: codesearcher: INFO: apiseq
2018-11-21 19:44:13,161: codesearcher: INFO: tokens


In [13]:
cb = cs._code_base

In [20]:
def f(i):
    print(cb[0][i])
    print("\n")
    r = np.concatenate((m[i],a[i],t[i]))
    print(r)

In [27]:
f(16)

public static String getNextTag ( String xmlData , int position ) { String nextTag = null ; if ( xmlData != null && ! xmlData . isEmpty ( ) && position < xmlData . length ( ) && xmlData . substring ( position ) . contains ( "<" ) ) { while ( xmlData . charAt ( position ) != '<' ) { position ++ ; } int startIndex = position ; if ( xmlData . substring ( position ) . contains ( ">" ) ) { while ( xmlData . charAt ( position ) != '>' ) { position ++ ; } nextTag = xmlData . substring ( startIndex , position + 1 ) ; } } return nextTag ; } 



[  2.  25. 168.   0.   0.   0.   3.  80.   3.  23.   3.  33.   3.  55.
   3.  33.   3.  55.   3.  33.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.  21.  71.  55.  42.  84.  10.
  46.  19. 130. 175.  56.  79.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.]


In [4]:
a,b,c,d = cs.load_transferred_training_chunk(0,10)

In [13]:
b[0][0]

6.3611593

In [5]:
[a,b,c,d]

[[array([ 1.7163925 ,  1.6568946 ,  1.3862827 , -0.7382604 ,  0.32439646,
         -1.6469766 ], dtype=float32),
  array([ 1.1686611 ,  0.5128617 ,  0.31767043, -1.8887786 , -0.8228126 ,
         -0.44375414], dtype=float32),
  array([-0.63839424, -2.4828732 , -3.511453  , -1.1108589 ,  1.4029664 ,
          4.6997733 ], dtype=float32),
  array([-0.15770455, -0.423064  , -0.7412222 ,  0.6331043 , -0.85758   ,
         -0.6406898 ], dtype=float32),
  array([-0.28955793,  6.9314337 ,  1.4682442 ,  1.6120253 ,  1.9796188 ,
          0.74076587], dtype=float32),
  array([-1.8773751, -1.1411294, -2.6988397, -2.4653528,  6.95955  ,
         -0.3880116], dtype=float32),
  array([ 2.8974438,  2.0290785,  2.5575864, -6.951726 , -0.2577041,
          2.5078652], dtype=float32),
  array([-1.3485634 , -0.8269628 , -1.564743  ,  0.48609486, -1.7132912 ,
         -0.7500962 ], dtype=float32),
  array([ 1.6185759 ,  1.5663148 ,  4.910299  , -6.1772304 , -0.47403607,
          2.4579577 ], dtype=float

In [9]:
e,f,g,h = cs.load_training_data_chunk(0,10)
e= cs.pad(e,6)
f=cs.pad(f,30)
g=cs.pad(f,50)

In [10]:
param = [e,f,g,h]

In [11]:
param

[array([[  82,   31,    0,    0,    0,    0],
        [ 262,    0,    0,    0,    0,    0],
        [1212,  176,    0,    0,    0,    0],
        [ 425,  118,   71,   59,    0,    0],
        [   3,  456,    0,    0,    0,    0],
        [ 847,  781,    0,    0,    0,    0],
        [ 872,    0,    0,    0,    0,    0],
        [   2,  244,   24,  169,    0,    0],
        [  62,   28,    0,    0,    0,    0],
        [1868,  180,  528,    0,    0,    0]]),
 array([[1004,  122,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0],
        [ 652, 2383, 1105, 7970,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0],
        [  73,    5,    3,   12,   30,    4,    2,   73,    5,    3,   12,
           30,    4,    6,   73,    5,    3,   